/* V0.31.4de — persistent work dock; canonical timer remains LifeRPGTime. */
(() => {
  "use strict";
  if (window.LifeRPGFocusDock) return;
  const time=window.LifeRPGTime,app=window.LifeRPGApp;
  if(!time?.getActive || !time?.getElapsedSeconds || !time?.finishActive || !app?.getState)return;
  const VERSION="0.31.4de";
  const preferencesKey="life-rpg-focus-dock-ui-de";
  const esc=x=>app.escapeHtml?.(String(x??""))??String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const dt=ms=>{const d=new Date(ms);return d.toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit",hour12:false});};
  const clock=sec=>{const s=Math.max(0,Math.floor(Number(sec)||0));return `${String(Math.floor(s/3600)).padStart(2,"0")}:${String(Math.floor(s%3600/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;};
  let prefs={x:null,y:null,compact:false,remind:45,seenId:""};
  try{prefs={...prefs,...JSON.parse(localStorage.getItem(preferencesKey)||"{}")} ;}catch(_){}
  const savePrefs=()=>{try{localStorage.setItem(preferencesKey,JSON.stringify(prefs));}catch(_){}};
  let dock=null,dialog=null,pipWindow=null,popupWindow=null,launcher=null,lastId="",wasRunning=false;
  const originalTitle=document.title;
  let lastReminder=null,returnNoticeFor=null;
  function active(){return time.getActive();}
  function totals(){const a=active();return a?time.getSessionPreview?.()||{durationSeconds:time.getElapsedSeconds(),rawSeconds:time.getElapsedSeconds()}:null;}
  function quickStart(kind){if(active())return;const choices={planning:{categoryId:"work_home",subcategory:"Lesson planning",label:"Unterrichtsplanung"},grading:{categoryId:"work_home",subcategory:"Grading / corrections",label:"Korrekturen"},admin:{categoryId:"school",subcategory:"School admin",label:"Schulorganisation"}};if(kind==="focus")time.startFocus?.({categoryId:"focus",subcategory:"Deep work",label:"Deep Work",minutes:50,breakMinutes:10});else time.startClock?.(choices[kind]||choices.planning);if(launcher)launcher.classList.remove("is-open");update(true);}
  function ensureLauncher(){if(launcher)return launcher;const div=document.createElement("div");div.id="lifeRpgFocusLauncher";div.className="focus-dock-launcher";div.innerHTML=`<button type="button" data-launch-toggle>▶ Timer starten</button><div class="focus-dock-launch-options"><button type="button" data-launch-kind="planning">Unterrichtsplanung</button><button type="button" data-launch-kind="grading">Korrekturen</button><button type="button" data-launch-kind="focus">Deep Work</button><button type="button" data-launch-kind="admin">Schulorganisation</button></div>`;document.body.appendChild(div);div.addEventListener("click",e=>{if(e.target.closest("[data-launch-toggle]"))div.classList.toggle("is-open");const b=e.target.closest("[data-launch-kind]");if(b)quickStart(b.dataset.launchKind);});launcher=div;return div;}
  function root(){if(dock)return dock;const div=document.createElement("aside");div.id="lifeRpgFocusDock";div.className="focus-dock";div.setAttribute("aria-label","Aktive Zeitmessung");div.innerHTML=`<div class="focus-dock-head" data-focus-drag><span class="focus-dock-beacon" aria-hidden="true">●</span><span class="focus-dock-eyebrow">LIVE RPG · ZEITERFASSUNG</span><div class="focus-dock-head-actions"><button type="button" data-focus-reminder title="Erinnerung bei laufendem Timer einstellen" aria-label="Timer-Erinnerung einstellen">♧</button><button type="button" data-focus-pip title="Externes Mini-Fenster" aria-label="Externes Mini-Fenster">↗</button><button type="button" data-focus-compact title="Kompakt anzeigen" aria-label="Kompakt anzeigen">−</button></div></div><div class="focus-dock-main"><strong data-focus-label></strong><div class="focus-dock-clock" data-focus-clock role="timer">00:00:00</div><small data-focus-state>Arbeitszeit wird erfasst</small><div class="focus-dock-controls"><button type="button" class="secondary-button" data-focus-pause>Ⅱ Pause</button><button type="button" class="primary-button" data-focus-stop>Stoppen & prüfen</button></div><div class="focus-dock-meta" data-focus-meta></div></div>`;document.body.appendChild(div);dock=div;drag(div);div.addEventListener("click",e=>{if(e.target.closest("[data-focus-pause]")){const a=active();if(a?.pausedAt)time.resumeActive?.();else time.pauseActive?.();update(true);}else if(e.target.closest("[data-focus-stop]")){if(pipWindow&&!pipWindow.closed){closeMini();window.focus?.();}if(active()?.mode==="break")time.finishActive();else review();}else if(e.target.closest("[data-focus-compact]")){prefs.compact=!prefs.compact;savePrefs();update(true);}else if(e.target.closest("[data-focus-pip]")){openMini();}else if(e.target.closest("[data-focus-reminder]")){configureReminder();}});return div;}
  function drag(el){let start=null;el.addEventListener("pointerdown",e=>{if(e.button!==0||!e.target.closest("[data-focus-drag]")||e.target.closest("button"))return;if(pipWindow && !pipWindow.closed)return;const box=el.getBoundingClientRect();start={id:e.pointerId,dx:e.clientX-box.left,dy:e.clientY-box.top};try{el.setPointerCapture(e.pointerId)}catch(_){}el.classList.add("dragging")});el.addEventListener("pointermove",e=>{if(!start||e.pointerId!==start.id)return;prefs.x=Math.min(window.innerWidth-el.offsetWidth-8,Math.max(8,e.clientX-start.dx));prefs.y=Math.min(window.innerHeight-el.offsetHeight-8,Math.max(8,e.clientY-start.dy));position()});const end=e=>{if(!start||e.pointerId!==start.id)return;start=null;el.classList.remove("dragging");savePrefs()};el.addEventListener("pointerup",end);el.addEventListener("pointercancel",end);}
  function position(){if(!dock||pipWindow&&!pipWindow.closed)return;if(Number.isFinite(prefs.x)&&Number.isFinite(prefs.y)){dock.style.left=`${Math.max(8,Math.min(window.innerWidth-dock.offsetWidth-8,prefs.x))}px`;dock.style.top=`${Math.max(8,Math.min(window.innerHeight-dock.offsetHeight-8,prefs.y))}px`;dock.style.right="auto";dock.style.bottom="auto";}}
  function update(force=false){const a=active();const el=root();el.classList.toggle("hidden",!a);if(!a){ensureLauncher().classList.remove("hidden");document.title=originalTitle;lastId="";closeMini();return;}ensureLauncher().classList.add("hidden");const id=a.id+":"+(a.pausedAt?"paused":"running")+":"+(prefs.compact?"small":"large");if(force||id!==lastId){lastId=id;el.classList.toggle("compact",prefs.compact);el.querySelector("[data-focus-label]").textContent=a.label||"Zeitmessung";el.querySelector("[data-focus-stop]").textContent=a.mode==="break"?"Pause beenden":"Stoppen & prüfen";el.querySelector("[data-focus-state]").textContent=a.pausedAt?"PAUSIERT · zählt nicht weiter":a.mode==="break"?"🌿 ERHOLUNGSPAUSE · keine Arbeitszeit":"● LÄUFT · zählt sekundengenau";const btn=el.querySelector("[data-focus-pause]");btn.textContent=a.pausedAt?"▶ Fortsetzen":"Ⅱ Pause";btn.setAttribute("aria-label",a.pausedAt?"Zeitmessung fortsetzen":"Zeitmessung pausieren");el.querySelector("[data-focus-compact]").textContent=prefs.compact?"＋":"−";el.querySelector("[data-focus-meta]").textContent=a.pausedAt?"Pause ist gespeichert. Die Uhr läuft erst nach Fortsetzen weiter.":a.mode==="focus"&&a.targetMinutes?`Fokusziel ${a.targetMinutes} min · Arbeitszeit wird weitergezählt, bis du stoppst.`:"Pausen kannst du abziehen, ohne deine echten Arbeitsminuten zu verlieren.";position();}
    el.querySelector("[data-focus-reminder]").title=prefs.remind?`Aktive Zeit: Erinnerung ca. alle ${prefs.remind} Minuten, sofern der Browser läuft und Benachrichtigungen erlaubt sind.`:"Erinnerungen ausgeschaltet";
    el.querySelector("[data-focus-clock]").textContent=clock(time.getElapsedSeconds());if(popupWindow&&!popupWindow.closed)paintPopup();document.title=`${a.pausedAt?"Ⅱ":"⏱"} ${clock(time.getElapsedSeconds())} · ${originalTitle}`;
  }
  function pauseToReview(){const a=active();if(!a)return false;wasRunning=!a.pausedAt;if(wasRunning)time.pauseActive?.();return true;}
  function ensureDialog(){if(dialog)return dialog;const d=document.createElement("dialog");d.id="lifeRpgTimerReview";d.className="focus-dock-review";d.innerHTML=`<form method="dialog"><header><span>✿ ZEITERFASSUNG</span><h2>Arbeitszeit prüfen</h2><p>Nur die tatsächlich gearbeiteten Abschnitte werden erfasst. Die Uhr ist während der Prüfung pausiert.</p></header><div class="focus-review-lines" data-review-lines></div><label>Ich habe bereits vor <span class="focus-review-inline"><input id="focusEndBack" type="number" min="0" step="1" value="0" inputmode="numeric"/> Minuten</span> aufgehört.<small>Für eine vergessene Mittagspause am Ende: kürzt den Arbeitsblock wirklich am Ende, statt eine Pause als Arbeitszeit zu zählen.</small></label><label>Weitere vergessene Pause abziehen <span class="focus-review-inline"><input id="focusOtherBreak" type="number" min="0" step="1" value="0" inputmode="numeric"/> Minuten</span><small>Nur falls eine Pause mitten im Block nicht mit Pause/Fortsetzen gestoppt wurde. Der Abzug wird gesondert dokumentiert.</small></label><div class="focus-review-result" aria-live="polite" data-review-total></div><p class="focus-review-error" data-review-error></p><footer><button class="secondary-button" type="button" data-review-hold>Pausiert lassen</button><button class="secondary-button" type="button" data-review-continue>▶ Weiterarbeiten</button><button class="primary-button" type="button" data-review-save>✓ Genau so erfassen</button></footer></form>`;document.body.appendChild(d);dialog=d;d.addEventListener("input",renderReview);d.addEventListener("click",e=>{if(e.target.closest("[data-review-save]"))commit();if(e.target.closest("[data-review-hold]"))d.close();if(e.target.closest("[data-review-continue]")){d.close();time.resumeActive?.();update(true);}});return d;}
  function values(){const endBack=Number(dialog?.querySelector("#focusEndBack")?.value||0),deduction=Number(dialog?.querySelector("#focusOtherBreak")?.value||0);if(!Number.isFinite(endBack)||endBack<0||!Number.isFinite(deduction)||deduction<0||!Number.isInteger(endBack)||!Number.isInteger(deduction))return null;return {endBackMinutes:endBack,deductionMinutes:deduction};}
  function renderReview(){if(!dialog?.open)return;const opts=values(),preview=opts?time.getSessionPreview?.(opts):null;const err=dialog.querySelector("[data-review-error]");err.textContent=!opts?"Bitte gültige, positive Minuten eingeben.":!preview?.durationSeconds?"Es bleibt keine Arbeitszeit übrig. Passe den Abzug an oder brich den Timer ohne Log ab.":"";const lines=dialog.querySelector("[data-review-lines]");const current=active();lines.innerHTML=`<div><small>Start</small><strong>${dt(current?.startedAt)}</strong></div><div><small>Arbeitsabschnitte</small><strong>${time.getSessionPreview?.()?.intervals.length||0}</strong></div><div><small>Gemessen (ohne getrackte Pausen)</small><strong>${clock(time.getSessionPreview?.()?.rawSeconds||0)}</strong></div>`;dialog.querySelector("[data-review-total]").textContent=`Tatsächliche Arbeitszeit: ${clock(preview?.durationSeconds||0)}`;dialog.querySelector("[data-review-save]").disabled=!!err.textContent;}
  function review(){if(!pauseToReview())return;const d=ensureDialog();d.querySelector("#focusEndBack").value="0";d.querySelector("#focusOtherBreak").value="0";if(!d.open)d.showModal?.();renderReview();update(true);}
  function commit(){const opts=values();if(!opts)return;const result=time.finishActive(opts);if(result?.ok){dialog.close();closeMini();update(true);}else{const error=dialog.querySelector("[data-review-error]");error.textContent=result?.reason||"Zeit wurde nicht erfasst. Bitte prüfe die Überschneidung im Zeitlog.";}}
  function miniMarkup(){return `<!doctype html><html lang="de"><head><meta charset="utf-8"><title>Life RPG · Zeiterfassung</title><link rel="stylesheet" href="./focus-dock.css?v=${VERSION}"></head><body class="focus-dock-popup"><main class="focus-popup-main"><small>✿ LIFE RPG · ZEITERFASSUNG</small><h2 id="timerPopupLabel"></h2><div id="timerPopupClock" role="timer">00:00:00</div><div id="timerPopupState"></div><footer><button id="timerPopupPause" type="button">Ⅱ Pause</button><button id="timerPopupStop" type="button">Stoppen & prüfen</button></footer><p>Die Daten bleiben in Life RPG. Dieses Safari-Fenster ist nicht garantiert immer im Vordergrund.</p></main></body></html>`;}
  function paintPopup(){if(!popupWindow||popupWindow.closed)return;try{const d=popupWindow.document,a=active();if(!a){popupWindow.close();return;}d.getElementById("timerPopupLabel").textContent=a.label||"Aktiver Timer";d.getElementById("timerPopupClock").textContent=clock(time.getElapsedSeconds());d.getElementById("timerPopupState").textContent=a.pausedAt?"PAUSIERT":"● LÄUFT";d.getElementById("timerPopupPause").textContent=a.pausedAt?"▶ Fortsetzen":"Ⅱ Pause";}catch(_){}}
  function makePopup(){popupWindow=window.open("","LifeRPGFocusTimer","popup=yes,width=375,height=285,scrollbars=yes,resizable=yes");if(!popupWindow){app.showToast?.("Der Browser hat das Mini-Fenster blockiert. Bitte Pop-ups für Life RPG erlauben.");return;}popupWindow.document.open();popupWindow.document.write(miniMarkup());popupWindow.document.close();popupWindow.document.getElementById("timerPopupPause").addEventListener("click",()=>{active()?.pausedAt?time.resumeActive?.():time.pauseActive?.();update(true);});popupWindow.document.getElementById("timerPopupStop").addEventListener("click",()=>{window.focus();review();});paintPopup();}
  async function configureReminder(){const choices=[45,30,60,0];const next=choices[(choices.indexOf(Number(prefs.remind))+1)%choices.length];prefs.remind=next;savePrefs();lastReminder=null;const message=next?`Erinnerung nach ${next} Minuten laufender Zeit. Browser muss geöffnet sein.`:"Timer-Erinnerungen ausgeschaltet.";if(next && "Notification" in window && Notification.permission==="default")try{await Notification.requestPermission();}catch(_){}app.showToast?.(message);update(true);}
  async function openMini(){if(!active())return;const dpi=window.documentPictureInPicture;if(dpi?.requestWindow){try{const w=await dpi.requestWindow({width:365,height:285});pipWindow=w;w.document.body.classList.add("focus-dock-pip");const link=w.document.createElement("link");link.rel="stylesheet";link.href=`./focus-dock.css?v=${VERSION}`;w.document.head.appendChild(link);w.document.body.appendChild(root());w.addEventListener("pagehide",()=>{pipWindow=null;document.body.appendChild(root());position();update(true);});update(true);return;}catch(e){console.warn("Document PiP not available",e);}}
    makePopup();}
  function closeMini(){if(pipWindow&&!pipWindow.closed){try{pipWindow.close()}catch(_){}}pipWindow=null;if(popupWindow&&!popupWindow.closed){try{popupWindow.close()}catch(_){}}popupWindow=null;if(dock&&dock.ownerDocument!==document)document.body.appendChild(dock);}
  function remind(){const a=active();if(!a||a.pausedAt||prefs.remind<=0){lastReminder=null;return;}const sec=time.getElapsedSeconds();const interval=Math.max(15,Number(prefs.remind))*60;if(sec<interval)return;const sequence=Math.floor(sec/interval),key=`${a.id}:${sequence}`;if(lastReminder===key)return;lastReminder=key;if(document.visibilityState==="visible")return; if("Notification" in window && Notification.permission==="granted"){try{new Notification("Life RPG · Läuft dein Arbeitstimer noch?",{body:"Arbeitszeit prüfen, Pause starten oder wie gewohnt fortsetzen.",tag:"life-rpg-work-reminder"});}catch(_){}}}
  function focusCheck(){const a=active();if(!a||a.pausedAt)return;const hiddenAt=Date.parse(a.lastHiddenAt||"");if(!Number.isFinite(hiddenAt)||Date.now()-hiddenAt<20*60000||returnNoticeFor===a.id)return;returnNoticeFor=a.id;app.showToast?.("Dein Arbeitstimer läuft noch. Hast du durchgearbeitet? Falls nicht: Stoppen & prüfen oder Pause starten.");}
  document.addEventListener("click",e=>{const control=e.target.closest?.("[data-week-stop],[data-time-stop],[data-universal-timer-finish],[data-week-pause],[data-week-resume],[data-time-pause],[data-time-resume]");if(!control||!active()||control.closest("#lifeRpgFocusDock,#lifeRpgTimerReview"))return;if(control.matches("[data-week-stop],[data-time-stop],[data-universal-timer-finish]")){e.preventDefault();e.stopImmediatePropagation();review();}else if(control.matches("[data-week-pause],[data-time-pause]")){e.preventDefault();e.stopImmediatePropagation();time.pauseActive?.();update(true);}else if(control.matches("[data-week-resume],[data-time-resume]")){e.preventDefault();e.stopImmediatePropagation();time.resumeActive?.();update(true);}},true);
  window.addEventListener("life-rpg:time-change",()=>update(true));
  const markHidden=()=>{const a=app.getState().timeTracking?.active;if(a){a.lastHiddenAt=new Date().toISOString();app.saveState({source:"focus-dock-hidden",suppressUiRefresh:true});}};
  document.addEventListener("visibilitychange",()=>{if(document.hidden)markHidden();else{focusCheck();update(true);}});
  window.addEventListener("pagehide",markHidden);
  window.addEventListener("focus",()=>{focusCheck();update(true);});window.addEventListener("resize",position);
  setInterval(()=>{update();remind();},1000);
  update(true);focusCheck();
  window.LifeRPGFocusDock={version:VERSION,review,openMini,refresh:()=>update(true),_test:{values,clock,root,update,renderReview,commit}};
})();
