/* Life RPG · Meine Woche V2 · v0.31.4cu. Scoped; existing weekPlanner and timeTracking data retained. */
(() => {
  'use strict';
  const app=window.LifeRPGApp, time=window.LifeRPGTime;
  if (!app || !time || !document.getElementById('view-week')) return;
  const TYPES={
    teaching:['Unterricht','school','Teaching',85,'teaching','slot'],
    supervision:['Aufsicht','school','Other school',20,'supervision','slot'],
    morning:['Gemeinsamer Anfang (GA)','school','Other school',20,'morning','slot'],
    lunch:['Mittagszeit','school','Other school',35,'lunch','slot'],
    substitutionTeaching:['Vertretung · Unterricht','school','Substitution',85,'teaching','plan'],
    substitutionSupervision:['Vertretung · Aufsicht','school','Substitution',20,'supervision','plan'],
    substitutionMorning:['Vertretung · GA','school','Substitution',20,'morning','plan'],
    substitutionLunch:['Vertretung · Mittagszeit','school','Substitution',35,'lunch','plan'],
    conference:['Konferenz / Besprechung','school','Conference / meeting',60,'conference','plan'],
    parents:['Elterngespräch','school','Other school',30,'conference','plan'],
    planning:['Unterrichtsplanung','work_home','Lesson planning',50,'planning','log'],
    grading:['Korrektur','work_home','Grading / corrections',45,'planning','log'],
    admin:['Schulorganisation','school','School admin',30,'admin','log'],
    other:['Anderes (Bestand)','other','Other',30,'other','legacy'],
    otherWork:['Sonstige Arbeitszeit','work_home','Other work',30,'other','log']
  };
  const DAYS=['Mo','Di','Mi','Do','Fr','Sa','So'],H0=6,H1=23,HPX=58, AUTO_MAX_DAYS=90;
  const $=id=>document.getElementById(id);
  const E=v=>app.escapeHtml?app.escapeHtml(String(v??'')):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const text=(id,value)=>{const n=$(id);if(n&&n.textContent!==String(value))n.textContent=String(value)};
  const html=(id,value)=>{const n=$(id);if(n&&n.innerHTML!==value)n.innerHTML=value};
  const kind=t=>TYPES[t]||TYPES.other;
  const key=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  const day=s=>{const [y,m,d]=String(s).split('-').map(Number);return new Date(y,m-1,d)};
  const plus=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
  const mon=d=>{const x=new Date(d.getFullYear(),d.getMonth(),d.getDate());x.setDate(x.getDate()-(x.getDay()+6)%7);return x};
  const hm=d=>d.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit',hour12:false});
  const nice=d=>d.toLocaleDateString('de-DE',{day:'2-digit',month:'short'});
  const duration=n=>`${Math.floor(n/60)?`${Math.floor(n/60)} h `:''}${Math.round(n%60)?`${Math.round(n%60)} min`:n%60===0?'':'0 min'}`.trim()||'0 min';
  const uid=()=>`wp-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;
  const epoch=s=>Date.parse(`${s}T12:00:00Z`);
  const startOf=(date,hhmm)=>{const d=day(date),[h,m]=hhmm.split(':').map(Number);d.setHours(h,m,0,0);return d};
  const mins=d=>d.getHours()*60+d.getMinutes();
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const fmtMin=n=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
  function parseHM(v){let s=String(v||'').trim();if(/^\d{1,2}$/.test(s))s=s.padStart(2,'0')+':00';else if(/^\d{3,4}$/.test(s))s=s.padStart(4,'0').replace(/^(\d\d)(\d\d)$/,'$1:$2');let match=/^(\d{1,2}):(\d{2})$/.exec(s);if(!match)return null;let h=+match[1],m=+match[2];return h<24&&m<60?fmtMin(h*60+m):null;}
  const clock=sec=>{let s=Math.max(0,Math.floor(+sec||0)),h=Math.floor(s/3600),m=Math.floor(s%3600/60);return h?`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`};
  let anchor=mon(new Date()),selected=null,pane='entries',editingPlanId=null,mode='plan',chosen='substitutionTeaching',draft=null,drag=null,syncing=false;
  function state(){const s=app.getState();if(!s.weekPlanner||typeof s.weekPlanner!=='object'||Array.isArray(s.weekPlanner))s.weekPlanner={schemaVersion:2,plans:[],appointments:[],exceptions:{}};let w=s.weekPlanner;w.plans=Array.isArray(w.plans)?w.plans:[];w.appointments=Array.isArray(w.appointments)?w.appointments:[];w.exceptions=w.exceptions&&typeof w.exceptions==='object'?w.exceptions:{};w.exceptions.days=w.exceptions.days&&typeof w.exceptions.days==='object'?w.exceptions.days:{};if(typeof w.autoEnabled!=='boolean')w.autoEnabled=true;if(!/^\d{4}-\d\d-\d\d$/.test(w.autoFrom||'')){w.autoFrom=key(new Date());app.saveState({source:'week-auto-anchor-init',suppressUiRefresh:true});}w.schemaVersion=2;return w;}
  const save=source=>{app.saveState({source:`week-${source}`});render();};
  const planAt=date=>state().plans.filter(p=>p.from<=date).sort((a,b)=>a.from.localeCompare(b.from)).at(-1)||null;
  const editable=()=>state().plans.find(p=>p.id===editingPlanId)||state().plans.slice().sort((a,b)=>a.from.localeCompare(b.from)).at(-1)||null;
  const daysOfWeek=()=>Array.from({length:7},(_,i)=>key(plus(anchor,i)));
  const sick=date=>{let h=app.getState().dailyPlanner?.days?.[date]?.checkIn?.health;return h?.illness==='yes'&&h?.sickLeave==='yes';};
  const off=date=>Boolean(state().exceptions.days[date])||sick(date);
  function occurrence(data,date,ref,origin,plan){const start=startOf(date,data.start),end=new Date(+start+Math.max(1,Number(data.minutes)||1)*60000);return {ref,date,start,end,label:data.label||kind(data.type)[0],type:data.type||'other',record:data.id,origin,planId:plan?.id||null,canceled:Boolean(state().exceptions[ref])||(origin==='slot'&&off(date))};}
  function scheduled(date){let p=planAt(date),wd=(day(date).getDay()+6)%7;let slots=(p?.slots||[]).filter(s=>s.weekday===wd).map(s=>occurrence(s,date,`slot:${p.id}:${s.id}:${date}`,'slot',p));let events=state().appointments.filter(a=>a.date<=date&&(a.repeat==='weekly'?( !a.until||date<=a.until)&&((epoch(date)-epoch(a.date))/86400000)%7===0:a.date===date)).map(a=>occurrence(a,date,`appointment:${a.id}:${date}`,'appointment'));return [...slots,...events].sort((a,b)=>a.start-b.start);}
  const actual=()=>time.getEntries().filter(e=>Number.isFinite(+new Date(e.startAt))&&Number.isFinite(+new Date(e.endAt)));
  function matching(o,logs){return logs.find(e=>e.weekPlannerRef===o.ref)||logs.find(e=>{let a=+new Date(e.startAt),b=+new Date(e.endAt);return Math.max(0,Math.min(b,+o.end)-Math.max(a,+o.start))/(+o.end- +o.start)>=.8&&e.categoryId===kind(o.type)[1]})||null;}
  function collision(o,logs){return logs.find(e=>Math.min(+new Date(e.endAt),+o.end)-Math.max(+new Date(e.startAt),+o.start)>0)||null;}
  function plannedConflict(date,start,minutes,ignoreId=null){const a=+startOf(date,start),b=a+minutes*60000;return scheduled(date).find(o=>!o.canceled&&o.record!==ignoreId&&+o.start<b&&+o.end>a)||null;}
  function byRef(ref){const date=String(ref).split(':').at(-1);return /^\d{4}-\d\d-\d\d$/.test(date)?scheduled(date).find(o=>o.ref===ref)||null:null;}
  const chooseOpts=(types,choice)=>types.map(k=>`<option value="${k}" ${k===choice?'selected':''}>${E(kind(k)[0])}</option>`).join('');
  function totals(logs,dates){let a=+day(dates[0]),b=+plus(day(dates[6]),1),part=logs.filter(e=>+new Date(e.startAt)<b&&+new Date(e.endAt)>a),minutes=e=>Math.max(0,Math.min(+new Date(e.endAt),b)-Math.max(+new Date(e.startAt),a))/60000,planned=dates.flatMap(scheduled).filter(e=>!e.canceled);return {work:Math.round(part.filter(e=>['school','work_home','focus'].includes(e.categoryId)).reduce((n,e)=>n+minutes(e),0)),all:Math.round(part.reduce((n,e)=>n+minutes(e),0)),done:planned.filter(e=>matching(e,part)).length,planned:planned.length};}
  function quick(date,logs){const s=app.getState(),linked=new Set(logs.map(e=>e.linkedQuestId).filter(Boolean)),on=at=>{let d=new Date(at);return Number.isFinite(+d)&&key(d)===date};return [...(s.externalCompletionLog||[]).filter(e=>on(e.at)).map(e=>({at:e.at,label:e.name||'Quick log'})),...(s.completionLog||[]).filter(e=>on(e.at)&&!linked.has(e.questId)).map(e=>({at:e.at,label:e.questName||'Quest'}))].sort((a,b)=>+new Date(a.at)-+new Date(b.at)).slice(0,30);}
  function dashboard(){if(!$('weekDashboard'))return;let dates=Array.from({length:7},(_,i)=>key(plus(mon(new Date()),i))),logs=actual(),t=totals(logs,dates),today=key(new Date());html('weekDashboardStats',`<span><b>${duration(t.work)}</b><small>Arbeit diese Woche</small></span><span><b>${t.done}/${t.planned}</b><small>Planblöcke erfasst</small></span>`);html('weekDashboardToday',scheduled(today).slice(0,5).map(o=>{let entry=matching(o,logs),clash=!entry&&collision(o,logs);return `<div><span>${hm(o.start)}</span><strong>${E(o.label)}</strong>${o.canceled?'<em>Entfallen</em>':entry?'<em>✓ Erfasst</em>':clash?'<em>⚠ Überschneidung</em>':+o.end<=Date.now()?`<button type="button" data-week-log="${E(o.ref)}">✓ Loggen</button>`:'<em>○ Geplant</em>'}</div>`;}).join('')||'<small>Heute keine Planblöcke.</small>');let node=$('weekDashboardTimer'),a=time.getActive();if(!node)return;if(!a){node.classList.add('hidden');node.dataset.activeId='';html('weekDashboardTimer','');return;}node.classList.remove('hidden');if(node.dataset.activeId!==String(a.id)){node.dataset.activeId=String(a.id);html('weekDashboardTimer',`<div class="week-dashboard-timer-copy"><span class="week-live-dot">●</span><div><small>Timer läuft · ${E(a.label)}</small><strong id="weekDashboardClock">${clock(time.getElapsedSeconds())}</strong></div></div><div class="week-timer-actions"><button type="button" class="primary-button" data-week-stop>Stoppen & erfassen</button><button type="button" class="secondary-button" data-week-cancel>Abbrechen · nicht erfassen</button></div>`);}}
  function color(e){return e.categoryId==='school'?'teaching':['work_home','focus'].includes(e.categoryId)?'planning':e.categoryId==='life_admin'?'home':e.categoryId==='recovery'?'rest':'hobby';}
  function lanes(blocks){let group=[],out=[],max=0;function flush(){if(!group.length)return;let ends=[];for(let b of group){let i=ends.findIndex(n=>n<=+b.start);if(i<0)i=ends.length;ends[i]=+b.end;b.lane=i;}for(let b of group){b.lanes=ends.length;out.push(b)}group=[];max=0}for(let b of blocks){if(group.length&&+b.start>=max)flush();group.push(b);max=Math.max(max,+b.end)}flush();return out;}
  function calendar(){const dates=daysOfWeek(),logs=actual(),t=totals(logs,dates);text('weekRange',`${nice(day(dates[0]))} – ${nice(day(dates[6]))} ${day(dates[6]).getFullYear()}`);html('weekSummary',`<article><small>Arbeitszeit erfasst</small><strong>${duration(t.work)}</strong></article><article><small>Alle Zeitlogs</small><strong>${duration(t.all)}</strong></article><article><small>Planblöcke bestätigt</small><strong>${t.done} / ${t.planned}</strong></article>`);html('weekDayHeaders',dates.map(date=>`<button type="button" data-week-day="${date}" class="week-day-head ${date===key(new Date())?'is-today':''}"><b>${DAYS[(day(date).getDay()+6)%7]}</b><span>${nice(day(date))}</span>${sick(date)?'<small>🤒 Krank</small>':state().exceptions.days[date]?'<small>Frei</small>':''}</button>`).join(''));html('weekHours',Array.from({length:H1-H0+1},(_,i)=>`<span style="top:${i*HPX}px">${String(i+H0).padStart(2,'0')}:00</span>`).join(''));
    html('weekColumns',dates.map(date=>{let planned=scheduled(date),logged=logs.filter(e=>key(new Date(e.startAt))===date),blocks=[...planned.map(o=>({start:o.start,end:o.end,title:o.label,ref:o.ref,tone:kind(o.type)[4],status:o.canceled?'canceled':matching(o,logs)?'logged':collision(o,logs)?'overlap':'planned',isAuto:!!matching(o,logs)?.weekPlannerAuto})),...logged.filter(e=>!planned.some(o=>!o.canceled&&e.weekPlannerRef===o.ref&&Math.abs(+new Date(e.startAt)- +o.start)<60000&&Math.abs(+new Date(e.endAt)- +o.end)<60000)).map(e=>({start:new Date(e.startAt),end:new Date(e.endAt),title:e.label||e.subcategory||'Zeitlog',entry:e.id,tone:color(e),status:'logged'}))];blocks.sort((a,b)=>a.start-b.start||a.end-b.end);let eventHTML=lanes(blocks).map(b=>{let a=mins(b.start),z=mins(b.end);if(z<=H0*60||a>=H1*60)return '';let top=(Math.max(H0*60,a)-H0*60)*HPX/60,height=Math.max(24,(Math.min(H1*60,z)-Math.max(H0*60,a))*HPX/60),w=100/b.lanes;return `<button type="button" class="week-event ${E(b.tone)} ${b.status}" style="top:${top}px;height:${height}px;left:calc(${b.lane*w}% + 2px);width:calc(${w}% - 4px)" ${b.ref?`data-week-ref="${E(b.ref)}"`:`data-week-entry="${E(b.entry)}"`} title="${E(b.title)} ${hm(b.start)}–${hm(b.end)}"><small>${hm(b.start)}–${hm(b.end)}</small><strong>${E(b.title)}</strong><em>${b.status==='logged'?(b.isAuto?'✓ Automatisch':'✓ Erfasst'):b.status==='canceled'?'Entfallen':b.status==='overlap'?'⚠ Überschneidung':'Geplant'}</em></button>`}).join(''),dots=quick(date,logs).map((e,i)=>{let at=new Date(e.at),m=mins(at);if(m<H0*60||m>=H1*60)return '';let top=(m-H0*60)*HPX/60+i%3*11;return `<span class="week-quick-chip" style="top:${top}px" title="Zeitpunkt des Logs (keine angenommene Dauer)">${hm(at)} · ${E(e.label)}</span>`;}).join('');return `<div class="week-day-col ${date===key(new Date())?'is-today':''}" data-week-grid-date="${date}" aria-label="${date}: Zum Planen klicken oder Zeitblock ziehen">${eventHTML}<div class="week-drag-preview" hidden></div><div class="week-quick-log">${dots}</div></div>`}).join(''));details();}
  function details(){let n=$('weekSelection');if(!n)return;if(!selected){n.innerHTML='<p>Block auswählen oder rechts eine Blockart wählen und im Kalender eine Zeit ziehen.</p>';return}if(selected.kind==='entry'){let e=actual().find(x=>x.id===selected.id);if(!e){selected=null;return details()}n.innerHTML=`<h3>${E(e.label)}</h3><p>${nice(new Date(e.startAt))} · ${hm(new Date(e.startAt))}–${hm(new Date(e.endAt))} · ${duration(e.minutes)}</p><p class="week-done-note">✓ Im Zeitlog erfasst ${e.reward?`· +${e.reward.xp||0} XP · +${e.reward.coins||0} Coins`:''}</p><button type="button" class="secondary-button" data-week-rhythm>Im Zeitlog bearbeiten →</button>`;return}let o=byRef(selected.id);if(!o){selected=null;return details()}let logs=actual(),log=matching(o,logs),clash=!log&&collision(o,logs),owned=log?.weekPlannerRef===o.ref;let actions='';if(o.canceled){actions=`<button type="button" class="secondary-button" data-week-restore="${E(o.ref)}" ${sick(o.date)?'disabled title="Krankmeldung zuerst im Tagescheck-in ändern"':''}>Ausfall zurücknehmen</button>`}else if(log){actions=owned?`<button type="button" class="secondary-button" data-week-skip="${E(o.ref)}">Als entfallen markieren · Log zurücknehmen</button>`:`<button type="button" class="secondary-button" data-week-rhythm>Bestehenden Zeitlog bearbeiten</button>`}else if(clash){actions=`<p>Ein Zeitlog überschneidet sich mit diesem Block. Keine doppelte Erfassung.</p><button type="button" class="secondary-button" data-week-rhythm>Im Zeitlog prüfen →</button>`}else{actions=`<button type="button" class="primary-button" data-week-log="${E(o.ref)}" ${+o.end>Date.now()?'disabled title="Erst nach Ende erfassen"':''}>✓ Als gearbeitet erfassen</button><button type="button" class="secondary-button" data-week-skip="${E(o.ref)}">Entfallen</button>`}n.innerHTML=`<h3>${E(o.label)}</h3><p>${DAYS[(day(o.date).getDay()+6)%7]} ${nice(day(o.date))} · ${hm(o.start)}–${hm(o.end)} · ${duration((o.end-o.start)/60000)}</p><p class="week-done-note">${o.canceled?'Entfallen · keine Arbeitszeit':log?'✓ Erfasst'+(log.reward?` · +${log.reward.xp||0} XP · +${log.reward.coins||0} Coins`:''):clash?'⚠ Überschneidung · nicht doppelt erfasst':'Nur geplant · keine Rewards'}</p><div class="week-detail-actions">${actions}${o.origin==='slot'?`<button type="button" class="secondary-button" data-week-plan-edit>Stundenplan ändern →</button>`:`<button type="button" class="secondary-button" data-week-appt-edit="${E(o.record)}">Termin bearbeiten</button><button type="button" class="secondary-button" data-week-appt-remove="${E(o.record)}">Terminserie löschen</button>`}</div>`;}
  function logOccurrence(ref){let o=byRef(ref);if(!o||o.canceled||+o.end>Date.now())return app.showToast?.('Dieser Block ist noch nicht abgeschlossen oder ist entfallen.');if(matching(o,actual()))return app.showToast?.('Dieser Zeitraum ist bereits erfasst.');let r=time.logInterval({startAt:o.start.toISOString(),endAt:o.end.toISOString(),label:o.label,categoryId:kind(o.type)[1],subcategory:kind(o.type)[2],sourceRef:o.ref});if(!r.ok)return app.showToast?.(r.reason);selected={kind:'occ',id:ref};render();app.showToast?.(`${o.label} · ${duration((o.end-o.start)/60000)} erfasst.`);}
  function removeOwned(ref,autoOnly=false){return time.removeWeekEntries({refs:[ref],autoOnly});}
  function skip(ref){let o=byRef(ref);if(!o)return;let e=matching(o,actual());if(e&&e.weekPlannerRef!==ref)return app.showToast?.('Ein unabhängiger Zeitlog überschneidet sich. Bitte zuerst im Zeitlog prüfen.');if(e&&!confirm(`„${o.label}“ als entfallen markieren und zugehörige Zeit/Rewards zurücknehmen?`))return;if(e)removeOwned(ref);state().exceptions[ref]=true;save('skip');}
  function restore(ref){const o=byRef(ref);if(o?.origin==='slot'&&sick(o.date))return app.showToast?.('Krankmeldung zuerst im Tagescheck-in ändern.');delete state().exceptions[ref];save('restore');reconcile();}
  function reconcile(){
    if(syncing)return;
    syncing=true;
    try{
      const w=state(),now=new Date(),today=key(now);
      // A later sick note/day-off must also retract an auto entry whose plan was edited.
      // Only week-owned AUTOMATIC entries are eligible; corrected/manual entries survive.
      let all=actual();
      const remove=all.filter(e=>e.weekPlannerAuto===true&&String(e.weekPlannerRef||'').startsWith('slot:')&&(
        off(key(new Date(e.startAt)))||Boolean(w.exceptions[e.weekPlannerRef])
      )).map(e=>e.weekPlannerRef);
      if(remove.length){time.removeWeekEntries({refs:[...new Set(remove)],autoOnly:true});all=actual();}
      if(!w.autoEnabled)return;
      const from=w.autoFrom<key(plus(now,-AUTO_MAX_DAYS))?key(plus(now,-AUTO_MAX_DAYS)):w.autoFrom;
      const specs=[];
      for(let d=day(from);key(d)<=today;d=plus(d,1)){
        for(const o of scheduled(key(d))){
          if(o.origin!=='slot'||o.canceled||+o.end>Date.now()||matching(o,all)||collision(o,all))continue;
          const spec={sourceRef:o.ref,startAt:o.start.toISOString(),endAt:o.end.toISOString(),label:o.label,categoryId:kind(o.type)[1],subcategory:kind(o.type)[2]};
          specs.push(spec);
          // Reserve an interval in this batch so two overlapping recurring slots never both pay.
          all.push({startAt:spec.startAt,endAt:spec.endAt,categoryId:spec.categoryId,weekPlannerRef:spec.sourceRef});
        }
      }
      if(specs.length)time.logWeekBatch(specs);
    }finally{syncing=false;}
  }
  function planSuggestion(date,type){return type==='conference'?'14:30':type==='parents'?'14:00':freeTime(date,kind(type)[3]);}
  function freeTime(date,length=30){
    // Clip cross-midnight saved time logs to this local calendar day.
    const low=+day(date),high=+plus(day(date),1);
    let occupied=[...scheduled(date).filter(o=>!o.canceled).map(o=>[mins(o.start),mins(o.end)]),...actual().filter(e=>+new Date(e.startAt)<high&&+new Date(e.endAt)>low).map(e=>[
      Math.max(0,Math.round((Math.max(+new Date(e.startAt),low)-low)/60000)),
      Math.min(1440,Math.round((Math.min(+new Date(e.endAt),high)-low)/60000))
    ])].filter(([a,b])=>b>a).sort((a,b)=>a[0]-b[0]);
    const today=date===key(new Date()),now=today?Math.ceil(mins(new Date())/5)*5:H0*60;
    if(!occupied.length)return fmtMin(clamp(now,H0*60,H1*60-5));
    let cursor=Math.max(occupied[0][1],H0*60);
    for(let i=1;i<occupied.length;i++){const [a,b]=occupied[i];if(a-cursor>=length)break;cursor=Math.max(cursor,b);}
    // Past work is allowed (backfill), so this remains the first usable gap
    // after a booked interval; never return an invalid 24:00 start.
    return fmtMin(clamp(cursor,H0*60,H1*60-5));
  }
  function formTypeOptions(){html('weekSlotType',chooseOpts(['teaching','supervision','morning','lunch'],'teaching'));html('weekApptType',chooseOpts(['substitutionTeaching','substitutionSupervision','substitutionMorning','substitutionLunch','conference','parents'],'conference'));html('weekManualType',chooseOpts(['planning','grading','admin','otherWork'],'planning'));html('weekDraftType',chooseOpts(mode==='plan'?['substitutionTeaching','substitutionSupervision','substitutionMorning','substitutionLunch','conference','parents']:['planning','grading','admin','otherWork'],chosen));}
  function sidebarMode(){html('weekPalette',Object.entries(TYPES).filter(([k,v])=>v[5]===mode).map(([k,v])=>`<button type="button" data-week-kind="${k}" class="week-palette-button ${chosen===k?'is-active':''}"><i class="${v[4]}"></i>${E(v[0])}<small>${v[3]} min</small></button>`).join(''));document.querySelectorAll('[data-week-mode]').forEach(b=>b.classList.toggle('is-active',b.dataset.weekMode===mode));text('weekPaletteHint',mode==='plan'?'Vertretungen, Konferenzen und Gespräche vorab planen. Erst nach Ende erfassen.':'Tatsächlich geleistete Arbeit direkt erfassen – auch rückwirkend.');$('weekDraft').classList.toggle('hidden',!draft);if(draft)populateDraft();}
  function openDraft(date,start,end){if(!chosen||!TYPES[chosen]||kind(chosen)[5]!==mode)chosen=mode==='plan'?'substitutionTeaching':'planning';draft={date,start:start||planSuggestion(date,chosen),minutes:Math.max(1,end?Math.max(5,Math.round((mins(startOf(date,end))-mins(startOf(date,start)))/5)*5):kind(chosen)[3]),type:chosen,label:''};if(!start)draft.minutes=kind(chosen)[3];if(!start)draft.start=mode==='plan'?planSuggestion(date,chosen):freeTime(date,draft.minutes);pane=mode==='plan'?'appointments':'entries';selected=null;render();$('weekDraft').scrollIntoView({block:'nearest',behavior:'smooth'});}
  function populateDraft(){if(!draft)return;html('weekDraftType',chooseOpts(mode==='plan'?['substitutionTeaching','substitutionSupervision','substitutionMorning','substitutionLunch','conference','parents']:['planning','grading','admin','otherWork'],draft.type));let f=$('weekDraftForm');f.elements.date.value=draft.date;f.elements.start.value=draft.start;f.elements.minutes.value=draft.minutes;f.elements.label.value=draft.label||'';f.elements.type.value=draft.type;text('weekDraftHeading',mode==='plan'?'Neuen Block planen':'Zeit direkt loggen');text('weekDraftEnd',`${draft.start} – ${fmtMin(mins(startOf(draft.date,draft.start))+draft.minutes)}`);$('weekDraftRepeatRow').classList.toggle('hidden',mode!=='plan');$('weekDraftUntilRow').classList.toggle('hidden',mode!=='plan'||f.elements.repeat.value!=='weekly');}
  function previewDraft(){const start=parseHM($('weekDraftStart').value),duration=+$('weekDraftMinutes').value;if(!start||!Number.isInteger(duration)||duration<1){text('weekDraftEnd','Beginn/Dauer prüfen.');return;}let end=mins(startOf('2000-01-01',start))+duration;text('weekDraftEnd',end<=1440?`${start} – ${fmtMin(end)} · ${duration} min`:'Ende muss am selben Tag liegen.');}
  function draftSubmit(ev){ev.preventDefault();if(!draft)return;let f=ev.currentTarget,v=new FormData(f),date=String(v.get('date')||''),start=parseHM(v.get('start')),minutes=+v.get('minutes'),type=String(v.get('type')||'other'),label=String(v.get('label')||'').trim()||kind(type)[0];if(!validDate(date)||!start||!Number.isInteger(minutes)||minutes<1||minutes>600||mins(startOf(date,start))+minutes>1440)return app.showToast?.('Datum, Uhrzeit (24 h) oder Dauer prüfen; Blöcke bleiben innerhalb eines Tages.');if(mode==='plan'){let repeat=v.get('repeat')==='weekly'?'weekly':'none',until=String(v.get('until')||'');if(until&&until<date)return app.showToast?.('Enddatum liegt vor Beginn.');let conflict=plannedConflict(date,start,minutes);if(conflict&&!confirm(`„${conflict.label}“ überschneidet sich mit diesem Block. Trotzdem einplanen?`))return;state().appointments.push({id:uid(),date,start,minutes,type,label,repeat,until:repeat==='weekly'?until:'',});save('plan-block');}else{let startAt=startOf(date,start),endAt=new Date(+startAt+minutes*60000),result=time.logInterval({startAt:startAt.toISOString(),endAt:endAt.toISOString(),categoryId:kind(type)[1],subcategory:kind(type)[2],label});if(!result.ok)return app.showToast?.(result.reason);}draft=null;render();app.showToast?.(mode==='plan'?'Block eingeplant. Noch nicht als Arbeitszeit erfasst.':'Arbeitszeit gespeichert.');}
  const validDate=s=>/^\d{4}-\d\d-\d\d$/.test(s)&&key(day(s))===s;
  function syncManualSuggestion(){let date=$('weekManualDate').value,type=$('weekManualType').value,minutes=Math.max(1,+$('weekManualMinutes').value||kind(type)[3]);if(!validDate(date))return;let a=freeTime(date,minutes);$('weekManualStart').value=a;text('weekManualSuggestion',`Vorschlag: ${a} Uhr · erster passender Platz nach dem ersten belegten Tagesblock. Du kannst die Zeit ändern.`);manualCalc();}
  function manualCalc(){$('weekManualMinutes').required=$('weekManualTiming').value!=='end';let start=parseHM($('weekManualStart').value),end=parseHM($('weekManualEnd').value),type=$('weekManualTiming').value,minutes=type==='end'&&start&&end?mins(startOf('2000-01-01',end))-mins(startOf('2000-01-01',start)):+$('weekManualMinutes').value;if(type==='end')$('weekManualEndRow').classList.remove('hidden');else $('weekManualEndRow').classList.add('hidden');$('weekManualMinutesRow').classList.toggle('hidden',type==='end');text('weekManualCalculated',start&&minutes>0?`${start} – ${fmtMin(mins(startOf('2000-01-01',start))+minutes)} · ${duration(minutes)}`:'Zeitraum prüfen (gleicher Tag).');}
  function manualSubmit(ev){ev.preventDefault();let f=ev.currentTarget,v=new FormData(f),date=String(v.get('date')||''),start=parseHM(v.get('start')),type=String(v.get('type')||'planning'),end=parseHM(v.get('end')),minutes=v.get('timing')==='end'&&start&&end?mins(startOf(date,end))-mins(startOf(date,start)):+v.get('minutes');if(!validDate(date)||!start||!Number.isInteger(minutes)||minutes<1||minutes>600||mins(startOf(date,start))+minutes>1440)return app.showToast?.('Bitte HH:MM im 24-Stunden-Format und Dauer am selben Tag prüfen.');let a=startOf(date,start),b=new Date(+a+minutes*60000),r=time.logInterval({startAt:a.toISOString(),endAt:b.toISOString(),categoryId:kind(type)[1],subcategory:kind(type)[2],label:String(v.get('label')||'').trim()||kind(type)[0]});if(!r.ok)return app.showToast?.(r.reason);render();app.showToast?.('Arbeitszeit gespeichert · Rewards im Activity Log.');}
  function appointmentSubmit(ev){ev.preventDefault();let f=ev.currentTarget,v=new FormData(f),date=String(v.get('date')||''),start=parseHM(v.get('start')),minutes=+v.get('minutes'),type=String(v.get('type')||'conference'),repeat=v.get('repeat'),until=String(v.get('until')||'');if(!validDate(date)||!start||minutes<1||minutes>600||mins(startOf(date,start))+minutes>1440)return app.showToast?.('Datum, Uhrzeit oder Dauer prüfen.');if(repeat==='weekly'&&until&&until<date)return app.showToast?.('Enddatum vor Beginn.');let conflict=plannedConflict(date,start,minutes,String(v.get('editId')||''));if(conflict&&!confirm(`„${conflict.label}“ überschneidet sich mit diesem Block. Trotzdem einplanen?`))return;let item={id:String(v.get('editId')||uid()),date,start,minutes,repeat:repeat==='weekly'?'weekly':'none',until:repeat==='weekly'?until:'',type,label:String(v.get('label')||'').trim()||kind(type)[0]},i=state().appointments.findIndex(a=>a.id===item.id);if(i>=0)state().appointments[i]=item;else state().appointments.push(item);f.reset();f.elements.editId.value='';f.elements.date.value=key(new Date());f.elements.type.value='conference';f.elements.minutes.value=60;f.elements.start.value='14:30';save('appointment');}
  function timetable(){let p=editable();html('weekPlanSelect','<option value="">Planversion auswählen</option>'+state().plans.slice().sort((a,b)=>a.from.localeCompare(b.from)).map(v=>`<option value="${E(v.id)}" ${v.id===p?.id?'selected':''}>${E(v.name)} · ab ${v.from}</option>`).join(''));text('weekPlanName',p?`${p.name} · ab ${nice(day(p.from))}`:'Noch kein Stundenplan');$('weekPlanEditor').classList.toggle('hidden',!p);html('weekPlanList',p?.slots?.length?p.slots.slice().sort((a,b)=>a.weekday-b.weekday||a.start.localeCompare(b.start)).map(s=>`<div class="week-plan-row"><span>${DAYS[s.weekday]} · ${E(s.start)} · ${s.minutes} min</span><strong>${E(s.label)}</strong><div><button type="button" data-week-slot-edit="${E(s.id)}">Ändern</button><button type="button" data-week-slot-remove="${E(s.id)}" aria-label="Stunde löschen">×</button></div></div>`).join(''):'<p class="muted">Hier kannst du die wöchentlich wiederkehrenden Stunden hinzufügen.</p>');}
  function createPlan(change){let from=$('weekPlanFrom').value,old=planAt(from);if(!validDate(from))return app.showToast?.('Bitte Startdatum wählen.');if(state().plans.some(p=>p.from===from))return app.showToast?.('Für dieses Datum existiert schon eine Version.');if(change&&!old)return app.showToast?.('Vor diesem Datum gibt es noch keinen Stundenplan.');let p={id:uid(),name:$('weekPlanTitle').value.trim()||(change?old.name:'Neuer Stundenplan'),from,slots:change?old.slots.map(s=>({...s,id:uid()})):[]};state().plans.push(p);editingPlanId=p.id;pane='schedule';save('new-plan');app.showToast?.(change?'Änderungsversion angelegt; alte Wochen bleiben erhalten.':'Neuer Stundenplan angelegt.');}
  function slotSubmit(ev){ev.preventDefault();let p=editable();if(!p)return;let f=ev.currentTarget,v=new FormData(f),minutes=+v.get('minutes'),start=parseHM(v.get('start')),type=String(v.get('type')||'teaching');if(!start||minutes<1||minutes>600||mins(startOf(p.from,start))+minutes>1440)return app.showToast?.('Beginn oder Dauer prüfen.');let sid=String(v.get('editId')||uid()),weekday=+v.get('weekday'),a=mins(startOf(p.from,start)),b=a+minutes,clash=p.slots.find(q=>q.id!==sid&&q.weekday===weekday&&mins(startOf(p.from,q.start))<b&&mins(startOf(p.from,q.start))+Number(q.minutes)>a);if(clash&&!confirm(`„${clash.label}“ überschneidet sich mit dieser Stunde. Trotzdem speichern?`))return;let slot={id:sid,weekday:+v.get('weekday'),start,minutes,type,label:String(v.get('label')||'').trim()||kind(type)[0]},i=p.slots.findIndex(s=>s.id===sid);if(i>=0)p.slots[i]=slot;else p.slots.push(slot);f.reset();f.elements.editId.value='';f.elements.minutes.value=85;f.elements.start.value='08:00';save('slot');reconcile();}
  function setDayOff(date){if(!validDate(date))return;let days=state().exceptions.days,was=!!days[date];if(sick(date))return app.showToast?.('Dieser Tag ist durch deine Krankmeldung bereits freigestellt.');if(was)delete days[date];else if(confirm(`Alle FESTEN Stundenplanblöcke für ${date} als entfallen markieren? Automatisch erfasste Zeit/Rewards werden zurückgenommen; andere Logs bleiben erhalten.`))days[date]=true;else return;if(!was)time.removeWeekEntries({date,autoOnly:true});save('day-off');if(was)reconcile();}
  function startTimer(type){if(time.getActive())return app.showToast?.('Es läuft bereits ein Timer.');const choices={planning:['work_home','Lesson planning','Unterrichtsplanung'],grading:['work_home','Grading / corrections','Korrekturen'],admin:['school','School admin','Schulorganisation']},spec=choices[type]||choices.planning;if(!confirm(`${spec[2]} jetzt als Timer starten? Du kannst ohne Zeitlog abbrechen.`))return;time.startClock({categoryId:spec[0],subcategory:spec[1],label:spec[2]});render();}
  function renderTimer(){let n=$('weekTimerCard'),a=time.getActive(),id=String(a?.id||'');if(n.dataset.activeId===id&&n.firstElementChild)return;n.dataset.activeId=id;html('weekTimerCard',a?`<span class="week-live-dot">●</span><div><small>Aktiver Timer · sekundenweise</small><strong>${E(a.label)}</strong><span id="weekLiveClock" role="timer">${clock(time.getElapsedSeconds())}</span></div><div class="week-timer-actions"><button type="button" class="primary-button" data-week-stop>Stoppen & erfassen</button><button type="button" class="secondary-button" data-week-cancel>Abbrechen · nicht erfassen</button></div>`:'<span>◷</span><div><strong>Kein Timer aktiv</strong><small>Unterrichtsplanung, Korrektur oder Organisation starten.</small></div>');}
  function render(){dashboard();if(!$('view-week').classList.contains('active'))return;calendar();timetable();renderTimer();sidebarMode();$('weekApptUntilRow').classList.toggle('hidden',$('weekApptRepeat').value!=='weekly');document.querySelectorAll('[data-week-tab]').forEach(b=>b.classList.toggle('is-active',b.dataset.weekTab===pane));document.querySelectorAll('[data-week-pane]').forEach(n=>n.classList.toggle('hidden',n.dataset.weekPane!==pane));let offDate=$('weekDayOffDate').value;text('weekDayOffStatus',validDate(offDate)?sick(offDate)?'🤒 Krankgemeldet · feste Stunden entfallen automatisch.':state().exceptions.days[offDate]?'Fester Stundenplan für diesen Tag freigestellt.':'Feste Stunden werden nach ihrem Ende automatisch erfasst.':'Datum wählen.');text('weekAutoState',state().autoEnabled?'An · ab '+state().autoFrom:'Pausiert');$('weekAutoToggle').checked=state().autoEnabled;}
  function dragInit(){const grid=$('weekColumns');let touchTimer=null,touchOrigin=null;
    const start=(col,y,pointerId)=>{let date=col.dataset.weekGridDate,rect=col.getBoundingClientRect(),startMin=clamp(Math.round((y-rect.top)/HPX*60/5)*5+H0*60,H0*60,H1*60-5);drag={col,date,startMin,endMin:startMin+5,pointerId};col.classList.add('is-dragging');paintDrag();};
    const paintDrag=()=>{if(!drag)return;let a=Math.min(drag.startMin,drag.endMin),b=Math.max(drag.startMin,drag.endMin);let box=drag.col.querySelector('.week-drag-preview');box.hidden=false;box.style.top=`${(a-H0*60)*HPX/60}px`;box.style.height=`${Math.max(8,(b-a)*HPX/60)}px`;box.textContent=`${fmtMin(a)} – ${fmtMin(b)}`;};
    const update=y=>{if(!drag)return;let rect=drag.col.getBoundingClientRect(),n=clamp(Math.round((y-rect.top)/HPX*60/5)*5+H0*60,H0*60,H1*60);drag.endMin=n;paintDrag();};
    const finish=()=>{if(!drag)return;let d=drag;drag=null;d.col.classList.remove('is-dragging');let box=d.col.querySelector('.week-drag-preview');if(box)box.hidden=true;let a=Math.min(d.startMin,d.endMin),b=Math.max(d.startMin,d.endMin);if(b-a<10)b=clamp(a+kind(chosen)[3],a+5,H1*60);openDraft(d.date,fmtMin(a),fmtMin(b));};
    grid.addEventListener('pointerdown',e=>{if(e.pointerType==='touch'||e.button!==0||e.target.closest('button'))return;let col=e.target.closest('[data-week-grid-date]');if(!col)return;start(col,e.clientY,e.pointerId);col.setPointerCapture(e.pointerId);e.preventDefault();});
    grid.addEventListener('pointermove',e=>{if(drag&&e.pointerId===drag.pointerId)update(e.clientY);});
    grid.addEventListener('pointerup',e=>{if(drag&&e.pointerId===drag.pointerId){update(e.clientY);finish();}});
    grid.addEventListener('pointercancel',e=>{if(drag&&drag.pointerId!=='touch'&&drag.pointerId===e.pointerId){drag.col.classList.remove('is-dragging');let box=drag.col.querySelector('.week-drag-preview');if(box)box.hidden=true;drag=null;}});
    grid.addEventListener('touchstart',e=>{if(e.touches.length!==1||e.target.closest('button'))return;let col=e.target.closest('[data-week-grid-date]');if(!col)return;let touch=e.touches[0];touchOrigin={col,x:touch.clientX,y:touch.clientY};touchTimer=setTimeout(()=>{if(touchOrigin){start(col,touchOrigin.y,'touch');navigator.vibrate?.(12);}},440);},{passive:true});
    grid.addEventListener('touchmove',e=>{if(drag?.pointerId==='touch'){e.preventDefault();update(e.touches[0]?.clientY??touchOrigin?.y??0);return;}if(touchOrigin&&e.touches[0]&&Math.hypot(e.touches[0].clientX-touchOrigin.x,e.touches[0].clientY-touchOrigin.y)>10){clearTimeout(touchTimer);touchOrigin=null;}},{passive:false});
    const endTouch=e=>{clearTimeout(touchTimer);if(drag?.pointerId==='touch'){if(e.changedTouches[0])update(e.changedTouches[0].clientY);finish();}else if(touchOrigin){openDraft(touchOrigin.col.dataset.weekGridDate,fmtMin(clamp(Math.round((touchOrigin.y-touchOrigin.col.getBoundingClientRect().top)/HPX*60/5)*5+H0*60,H0*60,H1*60-5)));}touchOrigin=null;};
    grid.addEventListener('touchend',endTouch);grid.addEventListener('touchcancel',()=>{clearTimeout(touchTimer);touchOrigin=null;if(drag?.pointerId==='touch'){drag.col.classList.remove('is-dragging');let box=drag.col.querySelector('.week-drag-preview');if(box)box.hidden=true;drag=null;}});
  }
  function bind(){for(const [id,n] of [['weekPrev',-7],['weekNext',7]])$(id).onclick=()=>{anchor=plus(anchor,n);selected=null;render();};$('weekToday').onclick=()=>{anchor=mon(new Date());selected=null;render();};
    document.querySelectorAll('[data-week-tab]').forEach(b=>b.addEventListener('click',()=>{pane=b.dataset.weekTab;render()}));
    document.querySelectorAll('[data-week-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.weekMode;chosen=mode==='plan'?'substitutionTeaching':'planning';draft=null;render();}));
    $('weekNewPlan').onclick=()=>createPlan(false);$('weekChangePlan').onclick=()=>createPlan(true);$('weekPlanSelect').addEventListener('change',()=>{editingPlanId=$('weekPlanSelect').value||null;render()});$('weekSlotForm').addEventListener('submit',slotSubmit);$('weekAppointmentForm').addEventListener('submit',appointmentSubmit);$('weekManualForm').addEventListener('submit',manualSubmit);$('weekDraftForm').addEventListener('submit',draftSubmit);
    [['weekSlotType','weekSlotMinutes'],['weekApptType','weekApptMinutes'],['weekManualType','weekManualMinutes']].forEach(([type,min])=>$(type).addEventListener('change',()=>{$(min).value=kind($(type).value)[3];if(type==='weekManualType')syncManualSuggestion();}));
    $('weekApptRepeat').addEventListener('change',()=>{$('weekApptUntilRow').classList.toggle('hidden',$('weekApptRepeat').value!=='weekly')});$('weekApptType').addEventListener('change',()=>{$('weekAppointmentForm').elements.start.value=planSuggestion($('weekApptDate').value||key(new Date()),$('weekApptType').value);});$('weekDraftRepeat').addEventListener('change',()=>{$('weekDraftUntilRow').classList.toggle('hidden',$('weekDraftRepeat').value!=='weekly')});$('weekDraftType').addEventListener('change',()=>{$('weekDraftMinutes').value=kind($('weekDraftType').value)[3];previewDraft();});['weekDraftStart','weekDraftMinutes'].forEach(id=>$(id).addEventListener('input',previewDraft));
    $('weekManualDate').addEventListener('change',syncManualSuggestion);$('weekManualTiming').addEventListener('change',manualCalc);$('weekManualStart').addEventListener('input',manualCalc);$('weekManualEnd').addEventListener('input',manualCalc);$('weekManualMinutes').addEventListener('input',manualCalc);$('weekDayOffDate').addEventListener('change',render);$('weekDayOffToggle').addEventListener('click',()=>setDayOff($('weekDayOffDate').value));$('weekAutoToggle').addEventListener('change',e=>{state().autoEnabled=e.target.checked;save('auto-toggle');if(e.target.checked)reconcile();});$('weekDraftClose').addEventListener('click',()=>{draft=null;render()});
    document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-week-open')){anchor=mon(new Date());selected=null;app.showView('week');render();return;}
      if(b.dataset.weekMode)return;
      if(b.dataset.weekKind){chosen=b.dataset.weekKind;draft=null;render();return;}
      if(b.dataset.weekDay){let date=b.dataset.weekDay;$('weekDayOffDate').value=date;if(mode==='plan'||mode==='log')openDraft(date);return;}
      if(b.dataset.weekRef){selected={kind:'occ',id:b.dataset.weekRef};details();return;}
      if(b.dataset.weekEntry){selected={kind:'entry',id:b.dataset.weekEntry};details();return;}
      if(b.dataset.weekLog){logOccurrence(b.dataset.weekLog);return;}
      if(b.dataset.weekSkip){skip(b.dataset.weekSkip);return;}
      if(b.dataset.weekRestore){restore(b.dataset.weekRestore);return;}
      if(b.hasAttribute('data-week-plan-edit')){let o=selected?.kind==='occ'?byRef(selected.id):null;editingPlanId=o?.planId||editingPlanId;pane='schedule';if(o)$('weekPlanFrom').value=o.date;render();if(o){let slot=editable()?.slots.find(s=>s.id===o.record);if(slot){let f=$('weekSlotForm');['weekday','start','minutes','type','label'].forEach(k=>f.elements[k].value=slot[k]);f.elements.editId.value=slot.id;f.scrollIntoView({block:'nearest',behavior:'smooth'});}}return;}
      if(b.dataset.weekApptEdit){let a=state().appointments.find(a=>a.id===b.dataset.weekApptEdit);if(!a)return;pane='appointments';render();let f=$('weekAppointmentForm');['id','date','start','minutes','type','label','repeat','until'].forEach(k=>{let field=f.elements[k==='id'?'editId':k];if(field)field.value=a[k]??'';});$('weekApptUntilRow').classList.toggle('hidden',a.repeat!=='weekly');f.scrollIntoView({block:'nearest',behavior:'smooth'});return;}
      if(b.dataset.weekApptRemove){if(confirm('Termin bzw. Wiederholungsserie entfernen? Bereits bestätigte Zeitlogs bleiben im Zeitlog.')){state().appointments=state().appointments.filter(a=>a.id!==b.dataset.weekApptRemove);selected=null;save('remove-appointment');}return;}
      if(b.dataset.weekSlotEdit){let s=editable()?.slots.find(s=>s.id===b.dataset.weekSlotEdit);if(s){let f=$('weekSlotForm');['weekday','start','minutes','type','label'].forEach(k=>f.elements[k].value=s[k]);f.elements.editId.value=s.id;f.scrollIntoView({block:'nearest',behavior:'smooth'});}return;}
      if(b.dataset.weekSlotRemove){let p=editable();if(p&&confirm('Stunde aus dieser Planversion entfernen? Für spätere Änderungen zuerst eine Änderungsversion anlegen.')){p.slots=p.slots.filter(s=>s.id!==b.dataset.weekSlotRemove);save('remove-slot');}return;}
      if(b.dataset.weekTimer){startTimer(b.dataset.weekTimer);return;}
      if(b.hasAttribute('data-week-stop')){if(time.getActive())time.finishActive();render();return;}
      if(b.hasAttribute('data-week-cancel')){if(time.getActive())time.cancelActive();render();return;}
      if(b.hasAttribute('data-week-rhythm')){app.showView('rhythm');return;}
    });
    document.querySelector('.nav-button[data-view="week"]')?.addEventListener('click',()=>{reconcile();render();});
    window.addEventListener('life-rpg:time-change',()=>{if(!syncing)render()});window.addEventListener('life-rpg:render',()=>{if(!syncing)render()});
    window.addEventListener('life-rpg:state-saved',e=>{let source=String(e.detail?.source||'');if(source==='daily-checkin-create'||source==='daily-briefing-edit'||source==='replace'||source==='cloud-restore'){reconcile();render();}});
    window.addEventListener('focus',()=>{reconcile();render()});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){reconcile();render();}});
    setInterval(()=>{if(document.visibilityState==='hidden')return;let active=time.getActive();if(active){let label=clock(time.getElapsedSeconds());for(let field of ['weekLiveClock','weekDashboardClock'])text(field,label);}let minute=Math.floor(Date.now()/60000);if(minute!==lastSyncMinute){lastSyncMinute=minute;reconcile();render();}},1000);
    dragInit();
  }
  let lastSyncMinute=-1;
  function init(){state();const today=key(new Date());$('weekPlanFrom').value=today;$('weekApptDate').value=today;$('weekManualDate').value=today;$('weekDayOffDate').value=today;formTypeOptions();$('weekManualMinutes').value=kind('planning')[3];syncManualSuggestion();bind();reconcile();render();}
  init();
  // Diagnostic surface for safe automated verification; does not mutate user data.
  window.LifeRPGWeekV2={getOccurrences:date=>scheduled(date).map(o=>({...o})),isSickDay:sick,suggestTime:freeTime,reconcile};
})();
