(() => {
"use strict";
const app=window.LifeRPGApp,time=window.LifeRPGTime;
if(!app||!time||!document.getElementById('view-week'))return;
const TYPES={
 teaching:['Unterricht','school','Teaching',45,'teaching'], supervision:['Aufsicht','school','Other school',20,'supervision'],
 morning:['Gemeinsamer Anfang (GA)','school','Other school',20,'morning'], lunch:['Mittagszeit','school','Other school',35,'lunch'],
 conference:['Konferenz / Besprechung','school','Conference / meeting',60,'conference'],
 admin:['Schulorganisation','school','School admin',30,'admin'], planning:['Unterrichtsplanung','work_home','Lesson planning',50,'planning'],
 grading:['Korrektur','work_home','Grading / corrections',50,'planning'], other:['Anderes','other','Other',30,'other']};
const DAYS=['Mo','Di','Mi','Do','Fr','Sa','So'];const H0=6,H1=23,HPX=58;
const $=id=>document.getElementById(id), E=v=>app.escapeHtml?app.escapeHtml(String(v??'')):String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const day=s=>{let [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)};
const plus=(d,n)=>{let x=new Date(d);x.setDate(x.getDate()+n);return x};
const mon=d=>{let x=new Date(d.getFullYear(),d.getMonth(),d.getDate());x.setDate(x.getDate()-(x.getDay()+6)%7);return x};
const hm=d=>d.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'});
const nice=d=>d.toLocaleDateString('de-DE',{day:'2-digit',month:'short'});
const dur=n=>n>=60?`${Math.floor(n/60)}h${n%60?` ${Math.round(n%60)}m`:''}`:`${Math.round(n)}m`;
const id=()=>`wp-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;
const kind=t=>TYPES[t]||TYPES.other;
const instant=(date,clock)=>{let d=day(date);let [h,m]=clock.split(':').map(Number);d.setHours(h,m,0,0);return d};
let anchor=mon(new Date()),selected=null,pane='entries',editingPlanId=null;
function state(){let s=app.getState();if(!s.weekPlanner||typeof s.weekPlanner!=='object'||Array.isArray(s.weekPlanner))s.weekPlanner={schemaVersion:1,plans:[],appointments:[],exceptions:{}};let p=s.weekPlanner;p.plans=Array.isArray(p.plans)?p.plans:[];p.appointments=Array.isArray(p.appointments)?p.appointments:[];p.exceptions=p.exceptions&&typeof p.exceptions==='object'?p.exceptions:{};return p;}
function save(label){app.saveState({source:`my-week-${label}`});render();}
const latest=()=>state().plans.slice().sort((a,b)=>a.from.localeCompare(b.from)).at(-1)||null;
const editPlan=()=>state().plans.find(p=>p.id===editingPlanId)||latest();
const planOn=d=>state().plans.filter(p=>p.from<=d).sort((a,b)=>a.from.localeCompare(b.from)).at(-1)||null;
const week=()=>Array.from({length:7},(_,i)=>key(plus(anchor,i)));
function eventFrom(s,date,ref,origin,plan=null){const start=instant(date,s.start),end=new Date(start.getTime()+Number(s.minutes)*60000);return {ref,date,start,end,label:s.label||kind(s.type)[0],type:s.type||'other',record:s.id,origin,planId:plan?.id,canceled:!!state().exceptions[ref]};}
function scheduled(date){const p=planOn(date),dow=(day(date).getDay()+6)%7;const slots=(p?.slots||[]).filter(s=>s.weekday===dow).map(s=>eventFrom(s,date,`slot:${p.id}:${s.id}:${date}`,'slot',p));const appointments=state().appointments.filter(a=>a.date<=date&&(a.repeat==='weekly'?( !a.until||date<=a.until)&&Math.round((day(date)-day(a.date))/86400000)%7===0:a.date===date)).map(a=>eventFrom(a,date,`appointment:${a.id}:${date}`,'appointment'));return [...slots,...appointments];}
const actual=()=>time.getEntries().filter(e=>Number.isFinite(new Date(e.startAt).getTime())&&Number.isFinite(new Date(e.endAt).getTime()));
function matching(o,logs){return logs.find(e=>e.weekPlannerRef===o.ref)||logs.find(e=>{let a=new Date(e.startAt).getTime(),b=new Date(e.endAt).getTime();let overlap=Math.max(0,Math.min(b,+o.end)-Math.max(a,+o.start));return overlap/(+o.end- +o.start)>=.8&&e.categoryId===kind(o.type)[1]})||null;}
function findRef(ref){const date=ref.split(':').at(-1);return scheduled(date).find(o=>o.ref===ref)||null;}
const displayOpts=(choice='teaching')=>Object.entries(TYPES).map(([k,v])=>`<option value="${k}" ${k===choice?'selected':''}>${E(v[0])}</option>`).join('');
function totals(logs,dates){let begin=day(dates[0]),end=plus(day(dates[6]),1),inWeek=logs.filter(e=>new Date(e.startAt)<end&&new Date(e.endAt)>begin);const minutes=e=>Math.max(0,Math.min(+new Date(e.endAt),+end)-Math.max(+new Date(e.startAt),+begin))/60000;let planned=dates.flatMap(d=>scheduled(d)).filter(o=>!o.canceled);return {work:Math.round(inWeek.filter(e=>['school','work_home','focus'].includes(e.categoryId)).reduce((s,e)=>s+minutes(e),0)),all:Math.round(inWeek.reduce((s,e)=>s+minutes(e),0)),done:planned.filter(o=>matching(o,inWeek)).length,planned:planned.length};}
function quick(date,logs){let s=app.getState(),linkIds=new Set(logs.map(e=>e.linkedQuestId).filter(Boolean)),on=at=>{let d=new Date(at);return Number.isFinite(+d)&&key(d)===date};return [...(s.externalCompletionLog||[]).filter(e=>on(e.at)).map(e=>({at:e.at,label:e.name||'Quick log'})),...(s.completionLog||[]).filter(e=>on(e.at)&&!linkIds.has(e.questId)).map(e=>({at:e.at,label:e.questName||'Quest'}))].sort((a,b)=>new Date(a.at)-new Date(b.at)).slice(0,30);}
function dashboard(){let node=$('weekDashboard');if(!node)return;let d=mon(new Date()),dates=Array.from({length:7},(_,i)=>key(plus(d,i))),logs=actual(),t=totals(logs,dates),tod=key(new Date());$('weekDashboardStats').innerHTML=`<span><b>${dur(t.work)}</b><small>Arbeit diese Woche</small></span><span><b>${t.done}/${t.planned}</b><small>Planblöcke erfasst</small></span>`;$('weekDashboardToday').innerHTML=scheduled(tod).slice(0,4).map(o=>`<div><span>${hm(o.start)}</span><strong>${E(o.label)}</strong>${matching(o,logs)?'<em>✓ Erfasst</em>':o.canceled?'<em>Entfallen</em>':+o.end<=Date.now()?`<button type="button" data-week-log="${E(o.ref)}" aria-label="${E(o.label)} als gearbeitet erfassen">✓ Loggen</button>`:'<em>○ Geplant</em>'}</div>`).join('')||'<small>Heute keine festen Blöcke hinterlegt.</small>';}
function color(e){return e.categoryId==='school'?'teaching':['work_home','focus'].includes(e.categoryId)?'planning':e.categoryId==='life_admin'?'home':e.categoryId==='recovery'?'rest':'hobby';}
function lanes(blocks){let group=[],max=0;const out=[];function flush(){if(!group.length)return;let ends=[];for(let b of group){let i=ends.findIndex(n=>n<=+b.start);if(i<0)i=ends.length;ends[i]=+b.end;b.lane=i;}group.forEach(b=>{b.lanes=ends.length;out.push(b)});group=[];max=0;}for(let b of blocks){if(group.length&&+b.start>=max)flush();group.push(b);max=Math.max(max,+b.end)}flush();return out;}
function calendar(){const dates=week(),logs=actual(),t=totals(logs,dates);$('weekRange').textContent=`${nice(day(dates[0]))} – ${nice(day(dates[6]))} ${day(dates[6]).getFullYear()}`;$('weekSummary').innerHTML=`<article><small>Arbeitszeit erfasst</small><strong>${dur(t.work)}</strong></article><article><small>Alle Zeitlogs</small><strong>${dur(t.all)}</strong></article><article><small>Geplante Blöcke bestätigt</small><strong>${t.done} / ${t.planned}</strong></article>`;
$('weekDayHeaders').innerHTML=dates.map(d=>`<div class="week-day-head ${d===key(new Date())?'is-today':''}"><b>${DAYS[(day(d).getDay()+6)%7]}</b><span>${nice(day(d))}</span></div>`).join('');
$('weekHours').innerHTML=Array.from({length:H1-H0+1},(_,i)=>`<span style="top:${i*HPX}px">${String(i+H0).padStart(2,'0')}:00</span>`).join('');
$('weekColumns').innerHTML=dates.map(date=>{let planned=scheduled(date),logged=logs.filter(e=>key(new Date(e.startAt))===date);let blocks=[...planned.map(o=>({start:o.start,end:o.end,title:o.label,ref:o.ref,tone:kind(o.type)[4],status:o.canceled?'canceled':matching(o,logs)?'logged':'planned'})),...logged.filter(e=>!planned.some(o=>matching(o,[e]))).map(e=>({start:new Date(e.startAt),end:new Date(e.endAt),title:e.label||e.subcategory||'Zeitlog',entry:e.id,tone:color(e),status:'logged'}))];blocks.sort((a,b)=>a.start-b.start||a.end-b.end);let items=lanes(blocks).map(b=>{let a=b.start.getHours()*60+b.start.getMinutes(),z=b.end.getHours()*60+b.end.getMinutes();if(z<=H0*60||a>=H1*60)return '';let top=(Math.max(H0*60,a)-H0*60)*HPX/60,height=Math.max(24,(Math.min(H1*60,z)-Math.max(H0*60,a))*HPX/60),w=100/b.lanes;return `<button type="button" class="week-event ${E(b.tone)} ${b.status}" style="top:${top}px;height:${height}px;left:calc(${b.lane*w}% + 2px);width:calc(${w}% - 4px)" ${b.ref?`data-week-ref="${E(b.ref)}"`:`data-week-entry="${E(b.entry)}"`} title="${E(b.title)} ${hm(b.start)}–${hm(b.end)}"><small>${hm(b.start)}–${hm(b.end)}</small><strong>${E(b.title)}</strong><em>${b.status==='logged'?'✓ Erfasst':b.status==='canceled'?'Entfallen':'Geplant'}</em></button>`;}).join('');let dots=quick(date,logs).map(e=>`<span title="Zeitpunkt des Logs (keine angenommene Dauer)">${hm(new Date(e.at))} · ${E(e.label)}</span>`).join('');return `<div class="week-day-col ${date===key(new Date())?'is-today':''}">${items}<div class="week-quick-log">${dots}</div></div>`;}).join('');details();}
function details(){let node=$('weekSelection');if(!selected){node.innerHTML='<p>Wähle einen Block im Kalender, um Arbeitszeit zu bestätigen oder einen Ausfall zu markieren.</p>';return;}if(selected.kind==='entry'){let e=actual().find(e=>e.id===selected.id);if(!e){selected=null;return details();}node.innerHTML=`<h3>${E(e.label)}</h3><p>${nice(new Date(e.startAt))} · ${hm(new Date(e.startAt))}–${hm(new Date(e.endAt))} · ${dur(e.minutes)}</p><p class="week-done-note">✓ Im Zeitlog erfasst ${e.reward?`· +${e.reward.xp||0} XP · +${e.reward.coins||0} Coins`:''}</p><button type="button" class="secondary-button" data-week-rhythm>Im Zeitlog bearbeiten →</button>`;return;}let o=findRef(selected.id);if(!o){selected=null;return details();}let log=matching(o,actual());node.innerHTML=`<h3>${E(o.label)}</h3><p>${DAYS[(day(o.date).getDay()+6)%7]} ${nice(day(o.date))} · ${hm(o.start)}–${hm(o.end)} · ${dur((o.end-o.start)/60000)}</p><p class="week-done-note">${log?'✓ Erfasst'+(log.reward?` · +${log.reward.xp||0} XP · +${log.reward.coins||0} Coins`:''):o.canceled?'Entfallen — keine Arbeitszeit':'Nur geplant — noch keine Belohnung'}</p><div class="week-detail-actions">${!log&&!o.canceled?`<button type="button" class="primary-button" data-week-log="${E(o.ref)}">✓ Als gearbeitet erfassen</button><button type="button" class="secondary-button" data-week-skip="${E(o.ref)}">Entfallen</button>`:''}${o.canceled?`<button type="button" class="secondary-button" data-week-restore="${E(o.ref)}">Ausfall zurücknehmen</button>`:''}${o.origin==='slot'?`<button type="button" class="secondary-button" data-week-plan-edit>Stundenplan ändern</button>`:`<button type="button" class="secondary-button" data-week-appt-remove="${E(o.record)}">Terminserie entfernen</button>`}</div>`;}
function logOccurrence(ref){let o=findRef(ref);if(!o||o.canceled)return;if(matching(o,actual()))return app.showToast?.('Dieser Zeitraum ist bereits erfasst.');let result=time.logInterval({startAt:o.start.toISOString(),endAt:o.end.toISOString(),label:o.label,categoryId:kind(o.type)[1],subcategory:kind(o.type)[2],sourceRef:o.ref});if(!result.ok){app.showToast?.(result.reason);return;}selected={kind:'occ',id:ref};render();app.showToast?.(`${o.label} · ${dur((o.end-o.start)/60000)} geloggt. Rewards über die bestehende Arbeitszeiterfassung.`);}
function timetable(){let p=editPlan();$('weekPlanSelect').innerHTML='<option value="">Planversion auswählen</option>'+state().plans.slice().sort((a,b)=>a.from.localeCompare(b.from)).map(item=>`<option value="${E(item.id)}" ${item.id===p?.id?'selected':''}>${E(item.name)} · ab ${E(item.from)}</option>`).join('');$('weekPlanName').textContent=p?`${p.name} · ab ${nice(day(p.from))}`:'Noch kein Stundenplan';$('weekPlanEditor').classList.toggle('hidden',!p);$('weekPlanList').innerHTML=p?.slots?.length?p.slots.slice().sort((a,b)=>a.weekday-b.weekday||a.start.localeCompare(b.start)).map(s=>`<div class="week-plan-row"><span>${DAYS[s.weekday]} · ${E(s.start)} · ${s.minutes}m</span><strong>${E(s.label)}</strong><div><button type="button" data-week-slot-edit="${E(s.id)}">Ändern</button><button type="button" data-week-slot-remove="${E(s.id)}">×</button></div></div>`).join(''):'<p class="muted">Neuen Stundenplan anlegen und wiederkehrende Stunden hinzufügen.</p>';}
function renderTimer(){let a=time.getActive();$('weekTimerCard').innerHTML=a?`<span class="week-live-dot">●</span><div><small>Aktiver Timer</small><strong>${E(a.label)}</strong><span id="weekLiveClock">${dur(Math.floor(time.getElapsedSeconds()/60))}</span></div><button type="button" class="primary-button" data-week-stop>Stoppen & erfassen</button>`:'<span>◷</span><div><strong>Kein Timer aktiv</strong><small>Starte unten mit einem Klick Planung, Korrektur oder Schulorganisation.</small></div>';}
function render(){dashboard();if(!$('view-week').classList.contains('active'))return;calendar();timetable();renderTimer();$('weekApptUntilRow').classList.toggle('hidden',$('weekApptRepeat').value!=='weekly');document.querySelectorAll('[data-week-tab]').forEach(b=>b.classList.toggle('is-active',b.dataset.weekTab===pane));document.querySelectorAll('[data-week-pane]').forEach(p=>p.classList.toggle('hidden',p.dataset.weekPane!==pane));}
function createPlan(change){let from=$('weekPlanFrom').value,old=planOn(from);if(!/^\d{4}-\d\d-\d\d$/.test(from))return app.showToast?.('Startdatum fehlt.');if(state().plans.some(p=>p.from===from))return app.showToast?.('Für diesen Tag existiert schon eine Planversion.');if(change&&!old)return app.showToast?.('Für diesen Tag gibt es noch keinen Stundenplan zum Übernehmen.');let name=$('weekPlanTitle').value.trim()||(change?old.name:'Neuer Stundenplan');let plan={id:id(),name,from,slots:change?old.slots.map(s=>({...s,id:id()})):[]};state().plans.push(plan);editingPlanId=plan.id;pane='schedule';save('timetable-new');app.showToast?.(change?'Neue Änderungsversion angelegt. Die frühere Version bleibt erhalten.':'Stundenplan angelegt.');}
function slotSubmit(ev){ev.preventDefault();let p=editPlan();if(!p)return;let f=ev.currentTarget,v=new FormData(f),minutes=Number(v.get('minutes')),start=String(v.get('start')||'');if(!/^\d\d:\d\d$/.test(start)||minutes<1||minutes>600)return app.showToast?.('Uhrzeit/Dauer prüfen.');let sid=v.get('editId')||id(),slot={id:sid,weekday:Number(v.get('weekday')),start,minutes,type:v.get('type'),label:String(v.get('label')||'').trim()||kind(v.get('type'))[0]};let i=p.slots.findIndex(s=>s.id===sid);if(i>=0)p.slots[i]=slot;else p.slots.push(slot);f.reset();f.elements.editId.value='';f.elements.minutes.value=45;save('timetable-slot');}
function appointmentSubmit(ev){ev.preventDefault();let v=new FormData(ev.currentTarget),date=v.get('date'),start=v.get('start'),minutes=Number(v.get('minutes')),repeat=v.get('repeat'),until=v.get('until');if(!/^\d{4}-\d\d-\d\d$/.test(date)||!/^\d\d:\d\d$/.test(start)||minutes<1||minutes>600)return app.showToast?.('Terminangaben prüfen.');if(repeat==='weekly'&&until&&until<date)return app.showToast?.('Enddatum vor Startdatum.');state().appointments.push({id:id(),date,start,minutes,repeat,until:repeat==='weekly'?until||'':null,type:v.get('type'),label:String(v.get('label')||'').trim()||kind(v.get('type'))[0]});ev.currentTarget.reset();$('weekApptDate').value=key(new Date());$('weekApptType').value='conference';$('weekApptMinutes').value=60;save('appointment');}
function manualSubmit(ev){ev.preventDefault();let v=new FormData(ev.currentTarget),a=new Date(v.get('start')),b=new Date(v.get('end')),t=kind(v.get('type'));if(!Number.isFinite(+a)||!Number.isFinite(+b))return app.showToast?.('Bitte Start und Ende prüfen.');let result=time.logInterval({startAt:a.toISOString(),endAt:b.toISOString(),categoryId:t[1],subcategory:t[2],label:String(v.get('label')||'').trim()||t[0]});if(!result.ok)return app.showToast?.(result.reason);render();app.showToast?.('Arbeitszeit gespeichert. Rewards im Activity Log.');}
function startTimer(which){if(time.getActive())return app.showToast?.('Es läuft bereits ein Timer.');let data=which==='planning'?['work_home','Lesson planning','Unterrichtsplanung',50,10]:which==='grading'?['work_home','Grading / corrections','Korrekturen',50,10]:['school','School admin','Schulorganisation',30,0];time.startFocus({categoryId:data[0],subcategory:data[1],label:data[2],minutes:data[3],breakMinutes:data[4]});render();app.showToast?.('Timer gestartet. Nach dem Stoppen erscheint der Zeitlog in der Wochenansicht.');}
function bind(){
$('weekPrev').onclick=()=>{anchor=plus(anchor,-7);selected=null;render()};$('weekNext').onclick=()=>{anchor=plus(anchor,7);selected=null;render()};$('weekToday').onclick=()=>{anchor=mon(new Date());selected=null;render()};
document.querySelectorAll('[data-week-tab]').forEach(b=>b.addEventListener('click',()=>{pane=b.dataset.weekTab;render()}));
$('weekNewPlan').onclick=()=>createPlan(false);$('weekChangePlan').onclick=()=>createPlan(true);
$('weekPlanSelect').addEventListener('change',()=>{editingPlanId=$('weekPlanSelect').value||null;render()});$('weekSlotForm').addEventListener('submit',slotSubmit);$('weekAppointmentForm').addEventListener('submit',appointmentSubmit);$('weekManualForm').addEventListener('submit',manualSubmit);
[['weekSlotType','weekSlotMinutes'],['weekApptType','weekApptMinutes']].forEach(([t,m])=>$(t).addEventListener('change',()=>{$(m).value=kind($(t).value)[3]}));$('weekApptRepeat').addEventListener('change',render);
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
if(b.dataset.weekOpen){anchor=mon(new Date());app.showView('week');render();}
if(b.dataset.weekRef){selected={kind:'occ',id:b.dataset.weekRef};details();}
if(b.dataset.weekEntry){selected={kind:'entry',id:b.dataset.weekEntry};details();}
if(b.dataset.weekLog)logOccurrence(b.dataset.weekLog);
if(b.dataset.weekSkip){state().exceptions[b.dataset.weekSkip]=true;save('skip');}
if(b.dataset.weekRestore){delete state().exceptions[b.dataset.weekRestore];save('restore');}
if(b.dataset.weekPlanEdit){editingPlanId=selected?.kind==='occ'?findRef(selected.id)?.planId:editingPlanId;pane='schedule';render();}
if(b.dataset.weekApptRemove&&confirm('Termin bzw. Wiederholungsserie entfernen?')){state().appointments=state().appointments.filter(a=>a.id!==b.dataset.weekApptRemove);selected=null;save('remove-appointment');}
if(b.dataset.weekSlotEdit){let s=editPlan()?.slots.find(x=>x.id===b.dataset.weekSlotEdit);if(s){let f=$('weekSlotForm');['weekday','start','minutes','type','label'].forEach(k=>f.elements[k].value=s[k]);f.elements.editId.value=s.id;f.scrollIntoView({block:'nearest',behavior:'smooth'});}}
if(b.dataset.weekSlotRemove&&confirm('Stunde aus der aktuellen Planversion entfernen? Für Änderungen ab neuem Datum zuerst „Änderungen übernehmen“ verwenden.')){let p=editPlan();p.slots=p.slots.filter(s=>s.id!==b.dataset.weekSlotRemove);save('remove-slot');}
if(b.dataset.weekTimer)startTimer(b.dataset.weekTimer);
if(b.dataset.weekStop){time.finishActive();render();}
if(b.dataset.weekRhythm)app.showView('rhythm');
});
document.querySelector('.nav-button[data-view="week"]')?.addEventListener('click',render);
window.addEventListener('life-rpg:time-change',render);window.addEventListener('life-rpg:render',render);
setInterval(()=>{let t=$('weekLiveClock');if(t&&$('view-week').classList.contains('active')){let label=dur(Math.floor(time.getElapsedSeconds()/60));if(t.textContent!==label)t.textContent=label;}},1000);
}
function init(){const date=key(new Date());$('weekPlanFrom').value=date;$('weekApptDate').value=date;$('weekManualStart').value=`${date}T15:00`;$('weekManualEnd').value=`${date}T15:45`;$('weekSlotType').innerHTML=displayOpts();$('weekApptType').innerHTML=displayOpts('conference');$('weekManualType').innerHTML=displayOpts('planning');bind();dashboard();}
init();
})();
